export type ViewId =
  | 'overview'
  | 'new-analysis'
  | 'analysis-in-progress'
  | 'analysis-result'
  | 'remediation-in-progress'
  | 'remediation-result'
  | 'history'
  | 'policies'
  | 'integrations'
